START
dataType mc
readTrigObject 0
puHistFile /afs/cern.ch/work/a/amodak/public/CSA14/CMSSW_7_0_7_patch1/src/15Sept2014/reweightFunctionFall12.root
histFile  test_CRSel_PHYS14DR_bx25.root
logFile   test_CRSel_PHYS14DR_bx25.out
eventFile test_CRSel_PHYS14DR_bx25.out
logOption 0
maxEvent -1
bunchX 25
vtxCutList ndf=4 z=24 Rho=2
muonCutList eta=2.4 pt=5. dxyPV=0.5 dzPV=1. SIP3D=4.
electronCutList pt=7. eta=2.5 dxyPV=0.5 dzPV=1. missingHits=1 SIP3D=4.
tauCutList eta=2.3 pt=10 dz=0.2 muVeto=0.5 eleVeto=0.5
bjetCutList eta=2.4 pt=20 useTCHE=0 TCHECut=3.3 SVHECut=1.74
jetCutList eta=4.7 pt=30 dRlep=0.4 btagFactor=0.814
evselCutList Isbkg=0 selectEvType=0 evType=1 CRtype=1 osCRtype=1
useTrigger 1
trigPathList HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v
trigPathList HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v
trigPathList HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v
trigPathList HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v
trigPathList HLT_TripleMu_12_10_5_v
trigPathList HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v
trigPathList HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v
trigPathList HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v
trigPathList HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v
trigPathList HLT_Ele32_eta2p1_WP75_Gsf_v
#inputFile /afs/cern.ch/work/s/sroychow/public/HZZ4l/CMSSW_7_2_0_patch1/src/DYJetsSkimmedCRminiAODtree.root
inputFile /afs/cern.ch/user/s/sroychow/work/sroychow/public/HZZ4l/forData/CMSSW_7_4_5/src/catsyncMC74/HZZ4lminiAOD_catsync.root
dumpGenInfo 0
useEventList 0
eventId 1 62212 6217573
END
