START
dataType mc
readTrk  0
readTrigObject 0
puHistFile /afs/cern.ch/work/a/amodak/public/CSA14/CMSSW_7_0_7_patch1/src/15Sept2014/reweightFunctionFall12.root
histFile  test_evetSelectn_PHYS14DR_PU20bx25_sigv3.root
logFile   test_evetSelectn_PHYS14DR_PU20bx25_sig.out
eventFile test_evetSelectn_PHYS14DR_PU20bx25_sig.out
createMVATree 0
mvaInputFile VH125_tmva_4.root
readMVA 0
logOption 0
maxEvent -1
bunchX 25
vtxCutList ndf=4 dxy=2 z=24
muonCutList eta=2.4 pt=5. nChambers=2 nMatches=2 nMatchedStations=2 dxyPV=0.5 dzPV=1. selectMutight=0
muonCutList pixHits=1 trkHits=8 globalChi2=10.0 trkD0=0.02 dB=0.02 vtxDistZ=0.2 dz=0.2 relIso=0.1
electronCutList pt=7. eta=2.5 dxyPV=0.5, dzPV=1.  selectEletight=0
electronCutList missingHits=1 dB=0.02 trkHits=8 pixHits=1 trkD0=0.02 dz=0.2 relIsoBarrel=0.15 relIsoEndCap=0.1
electronCutList etaLow=1.4442 etaUp=1.566 scEtaLow=1.4442 scEtaUp=1.566 eleId=7
photonCutList pt=2.
tauCutList eta=2.3 pt=10 dz=0.2 muVeto=0.5 eleVeto=0.5
bjetCutList eta=2.4 pt=20 useTCHE=0 TCHECut=3.3 SVHECut=1.74
evselCutList Isbkg=0
evselCutList drMuTau=0.5 drTauTau=0.5 drEleTau=0.5 ptTau1=20 ptTau2=20 muVetoPt=15 eleVetoPt=15 etaTau1=2.3 etaTau2=2.3
evselCutList dzMuTauVtx=0.14 dzTauTauVtx=0.14 dzEleTauVtx=0.14 eTauMass=80 tauPairPt=50
evselCutList maxPtDiff=20 maxDr=0.1 massLow=30 massHigh=120 tagPt=15 maxMET=30
evselCutList mZ1lowbound=40. mZ1upperbound=120. mZ2lowbound=12. mZ2upperbound=120.
useTrigger 0
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_1.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_2.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_3.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_4.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_5.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_6.root
inputFile  /home/sroychow/HZZ4lAnalysis/anaTrees/newP14_v3/HZZ4lPU20bx25/HZZ4lminiAODtree_7.root
END
